import { supabase } from './supabase'
import type { ListPhase, ListPosition, Participant, Payment, Pelada, PeladaSeries, PlayerType, Profile, RankingRow, Role } from './database.types'

export async function nextPelada() { const { data, error } = await supabase.from('peladas').select('*').gte('data', new Date().toISOString().slice(0, 10)).neq('status', 'cancelada').order('data').order('horario').limit(1).maybeSingle(); if (error) throw error; return data as Pelada | null }
export async function participants(peladaId: string) { const { data, error } = await supabase.from('pelada_participantes').select('*, profile:profiles!user_id(*)').eq('pelada_id', peladaId).neq('status', 'cancelado').order('ordem_entrada'); if (error) throw error; return data as Participant[] }
export async function joinPelada(peladaId: string) { const { data, error } = await supabase.rpc('entrar_na_pelada', { p_pelada_id: peladaId }); if (error) throw error; return data as string }
export async function leavePelada(peladaId: string) { const { error } = await supabase.rpc('sair_da_pelada', { p_pelada_id: peladaId }); if (error) throw error }
export async function rankings() { const { data, error } = await supabase.from('ranking_eventos').select('user_id,tipo,pontos,profile:profiles!user_id(*)'); if (error) throw error; const totals = new Map<string, RankingRow>(); for (const row of data ?? []) { const key = `${row.tipo}:${row.user_id}`; const old = totals.get(key); totals.set(key, { user_id: row.user_id, tipo: row.tipo, pontos: (old?.pontos ?? 0) + row.pontos, profile: Array.isArray(row.profile) ? row.profile[0] : row.profile } as RankingRow) } return [...totals.values()] }
export async function profileStats(userId: string) { const [{ data: games, error: gamesError }, { data: awards, error: awardsError }] = await Promise.all([supabase.from('pelada_participantes').select('status').eq('user_id', userId).in('status', ['presente', 'faltou']), supabase.from('premiacoes').select('id,categoria').eq('user_id', userId)]); if (gamesError) throw gamesError; if (awardsError) throw awardsError; return { participacoes: games?.length ?? 0, presencas: games?.filter(x => x.status === 'presente').length ?? 0, faltas: games?.filter(x => x.status === 'faltou').length ?? 0, premiacoes: awards ?? [] } }
export async function adminSummary() { const pelada = await nextPelada(); const [list, profiles, payments] = await Promise.all([pelada ? participants(pelada.id) : [], supabase.from('profiles').select('*').eq('mensalista_ativo', true), supabase.from('pagamentos').select('id').in('status', ['pendente', 'atrasado'])]); if (profiles.error) throw profiles.error; if (payments.error) throw payments.error; return { pelada, list, mensalistas: profiles.data.length, pendentes: payments.data.length } }
export async function savePelada(values: Partial<Pelada> & Pick<Pelada, 'data' | 'horario' | 'local' | 'limite_jogadores'>) { const { error } = values.id ? await supabase.from('peladas').update(values).eq('id', values.id) : await supabase.from('peladas').insert(values); if (error) throw error }
export async function allProfiles() { const { data, error } = await supabase.from('profiles').select('*').order('nome'); if (error) throw error; return data as Profile[] }
export async function setPlayerType(id: string, tipo: PlayerType, posicao: ListPosition) { const { error } = await supabase.rpc('admin_definir_jogador', { p_user_id: id, p_tipo: tipo, p_posicao: posicao }); if (error) throw error }
export async function setListPhase(id: string, fase: ListPhase) { const { error } = fase === 'mensalistas' ? await supabase.rpc('abrir_lista_mensalistas', { p_pelada_id: id }) : await supabase.rpc('definir_fase_lista', { p_pelada_id: id, p_fase: fase }); if (error) throw error }
export async function respondPelada(id: string, vai: boolean) { const { data, error } = await supabase.rpc('responder_pelada', { p_pelada_id: id, p_vai: vai }); if (error) throw error; return data as string }
export async function updateOwnProfile(values: Pick<Profile,'nome'|'apelido'|'telefone'|'foto_url'>) { const { error } = await supabase.from('profiles').update(values).eq('id', (await supabase.auth.getUser()).data.user?.id); if (error) throw error }
export async function createUser(values: { nome:string; email:string; role:Role; tipo_jogador:PlayerType; posicao_lista:ListPosition }) { const { data, error } = await supabase.functions.invoke('create-user', { body: values }); if (error) throw error; if (data?.error) throw new Error(data.error) }
export async function activeSeries() { const { data,error }=await supabase.from('pelada_series').select('*').eq('ativa',true).limit(1).maybeSingle();if(error)throw error;return data as PeladaSeries|null }
export async function saveSeries(values:Omit<PeladaSeries,'id'> & {id?:string}) { const {error}=values.id?await supabase.from('pelada_series').update(values).eq('id',values.id):await supabase.from('pelada_series').insert(values);if(error)throw error }
export async function generateNextPelada(id:string){const {error}=await supabase.rpc('gerar_proxima_pelada',{p_serie_id:id});if(error)throw error}
export async function adminParticipant(peladaId: string, userId: string, action: 'add' | 'remove' | 'promote' | 'presente' | 'faltou') { const { error } = await supabase.rpc('admin_gerenciar_participante', { p_pelada_id: peladaId, p_user_id: userId, p_acao: action }); if (error) throw error }
export async function payments() { const { data, error } = await supabase.from('pagamentos').select('*, profile:profiles!user_id(*)').order('created_at', { ascending: false }); if (error) throw error; return data as Payment[] }
export async function savePayment(values: Omit<Payment, 'id' | 'created_at' | 'profile'>) { const { error } = await supabase.from('pagamentos').insert(values); if (error) throw error }
