import { supabase } from './supabase'
import type { Expense, ListPhase, ListPosition, Participant, Payment, Pelada, PeladaSeries, Player, PlayerType, Profile, RankingRow, Role, TeamMember } from './database.types'

export async function nextPelada() { let result=await supabase.from('peladas').select('*').gte('data',new Date().toISOString().slice(0,10)).neq('status','cancelada').order('data').order('horario').limit(1).maybeSingle();if(result.error)throw result.error;if(result.data){const {error}=await supabase.rpc('sincronizar_fase_lista',{p_pelada_id:result.data.id});if(error)throw error;result=await supabase.from('peladas').select('*').eq('id',result.data.id).single()}if(result.error)throw result.error;return result.data as Pelada|null }
export async function participants(peladaId: string) { const { data, error } = await supabase.from('pelada_participantes').select('*, profile:profiles!user_id(*), player:jogadores!jogador_id(*)').eq('pelada_id', peladaId).neq('status', 'cancelado').order('ordem_entrada'); if (error) throw error; return data as Participant[] }
export async function joinPelada(peladaId: string) { const { data, error } = await supabase.rpc('entrar_na_pelada', { p_pelada_id: peladaId }); if (error) throw error; return data as string }
export async function leavePelada(peladaId: string) { const { error } = await supabase.rpc('sair_da_pelada', { p_pelada_id: peladaId }); if (error) throw error }
export async function rankings() { const { data, error } = await supabase.from('ranking_eventos').select('user_id,tipo,pontos,profile:profiles!user_id(*)'); if (error) throw error; const totals = new Map<string, RankingRow>(); for (const row of data ?? []) { const key = `${row.tipo}:${row.user_id}`; const old = totals.get(key); totals.set(key, { user_id: row.user_id, tipo: row.tipo, pontos: (old?.pontos ?? 0) + row.pontos, profile: Array.isArray(row.profile) ? row.profile[0] : row.profile } as RankingRow) } return [...totals.values()] }
export async function profileStats(userId: string) { const [{ data: games, error: gamesError }, { data: awards, error: awardsError }] = await Promise.all([supabase.from('pelada_participantes').select('status').eq('user_id', userId).in('status', ['presente', 'faltou']), supabase.from('premiacoes').select('id,categoria').eq('user_id', userId)]); if (gamesError) throw gamesError; if (awardsError) throw awardsError; return { participacoes: games?.length ?? 0, presencas: games?.filter(x => x.status === 'presente').length ?? 0, faltas: games?.filter(x => x.status === 'faltou').length ?? 0, premiacoes: awards ?? [] } }
export async function adminSummary() { const pelada = await nextPelada(); const [list, profiles, payments] = await Promise.all([pelada ? participants(pelada.id) : [], supabase.from('profiles').select('*').eq('mensalista_ativo', true), supabase.from('pagamentos').select('id').in('status', ['pendente', 'atrasado'])]); if (profiles.error) throw profiles.error; if (payments.error) throw payments.error; return { pelada, list, mensalistas: profiles.data.length, pendentes: payments.data.length } }
export async function savePelada(values: Partial<Pelada> & Pick<Pelada, 'data' | 'horario' | 'local' | 'limite_jogadores'>) { const { error } = values.id ? await supabase.from('peladas').update(values).eq('id', values.id) : await supabase.from('peladas').insert(values); if (error) throw error }
export async function allProfiles() { const { data, error } = await supabase.from('profiles').select('*').order('nome'); if (error) throw error; return data as Profile[] }
export async function allPlayers(){const {data,error}=await supabase.from('jogadores').select('*, profile:profiles!user_id(*)').eq('ativo',true).order('nome');if(error)throw error;return data as Player[]}
export async function myPlayer(){const user=(await supabase.auth.getUser()).data.user;if(!user)return null;const {data,error}=await supabase.from('jogadores').select('*').eq('user_id',user.id).eq('ativo',true).maybeSingle();if(error)throw error;return data as Player|null}
export async function savePlayer(values:{id?:string;nome:string;tipo:PlayerType;posicao:ListPosition;user_id?:string|null}){const {error}=await supabase.rpc('salvar_jogador',{p_id:values.id??null,p_nome:values.nome,p_tipo:values.tipo,p_posicao:values.posicao,p_user_id:values.user_id??null});if(error)throw error}
export async function importWhatsAppList(peladaId:string,items:{nome:string;grupo:string}[]){const {data,error}=await supabase.rpc('importar_lista_whatsapp',{p_pelada_id:peladaId,p_itens:items});if(error)throw error;return data as number}
export async function setPlayerType(id: string, tipo: PlayerType, posicao: ListPosition) { const { error } = await supabase.rpc('admin_definir_jogador', { p_user_id: id, p_tipo: tipo, p_posicao: posicao }); if (error) throw error }
export async function setListPhase(id: string, fase: ListPhase) { const { error }=await supabase.rpc('definir_fase_lista',{p_pelada_id:id,p_fase:fase});if(error)throw error }
export async function reactivateAutomaticList(id:string){const {error}=await supabase.rpc('reativar_lista_automatica',{p_pelada_id:id});if(error)throw error}
export async function respondPelada(id: string, vai: boolean) { const { data, error } = await supabase.rpc('responder_pelada', { p_pelada_id: id, p_vai: vai }); if (error) throw error; return data as string }
export async function updateOwnProfile(values: Pick<Profile,'nome'|'apelido'|'telefone'|'foto_url'>) { const { error } = await supabase.from('profiles').update(values).eq('id', (await supabase.auth.getUser()).data.user?.id); if (error) throw error }
export async function uploadAvatar(file:File){const user=(await supabase.auth.getUser()).data.user;if(!user)throw new Error('Não autenticado');if(file.size>5*1024*1024)throw new Error('A foto deve ter até 5 MB.');if(!['image/jpeg','image/png','image/webp'].includes(file.type))throw new Error('Use uma imagem JPG, PNG ou WEBP.');const path=`${user.id}/avatar`;const {error}=await supabase.storage.from('avatars').upload(path,file,{contentType:file.type,upsert:true});if(error)throw error;return `${supabase.storage.from('avatars').getPublicUrl(path).data.publicUrl}?v=${Date.now()}`}
export async function createUser(values: { nome:string; email:string; password:string; role:Role; tipo_jogador:PlayerType; posicao_lista:ListPosition }) { const { data, error } = await supabase.functions.invoke('create-user', { body: values }); if (error) throw error; if (data?.error) throw new Error(data.error) }
export async function resetUserPassword(userId:string,password:string){const {data,error}=await supabase.functions.invoke('create-user',{body:{action:'reset',user_id:userId,password}});if(error)throw error;if(data?.error)throw new Error(data.error)}
export async function manageUser(values:{user_id:string;role:Role;jogador_id:string|null}){const {error}=await supabase.rpc('superadmin_gerenciar_usuario',{p_user_id:values.user_id,p_role:values.role,p_jogador_id:values.jogador_id});if(error)throw error}
export async function activeSeries() { const { data,error }=await supabase.from('pelada_series').select('*').eq('ativa',true).limit(1).maybeSingle();if(error)throw error;return data as PeladaSeries|null }
export async function saveSeries(values:Omit<PeladaSeries,'id'> & {id?:string}) { const {error}=values.id?await supabase.from('pelada_series').update(values).eq('id',values.id):await supabase.from('pelada_series').insert(values);if(error)throw error }
export async function generateNextPelada(id:string){const {error}=await supabase.rpc('gerar_proxima_pelada',{p_serie_id:id});if(error)throw error}
export async function saveFinanceConfig(id:string,values:{valor_mensalista:number;valor_avulso:number;dia_vencimento:number;chave_pix:string}){const {error}=await supabase.from('pelada_series').update(values).eq('id',id);if(error)throw error}
export async function generateMonthlyCharges(seriesId:string,competencia:string){const {data,error}=await supabase.rpc('gerar_mensalidades',{p_serie_id:seriesId,p_competencia:competencia});if(error)throw error;return data as number}
export async function settleMonthlyCharges(competencia:string){const {data,error}=await supabase.rpc('quitar_mensalidades_mes',{p_competencia:competencia});if(error)throw error;return data as number}
export async function generateCasualCharges(peladaId:string,seriesId:string){const {data,error}=await supabase.rpc('gerar_cobrancas_avulsas',{p_pelada_id:peladaId,p_serie_id:seriesId});if(error)throw error;return data as number}
export async function updatePayment(id:string,status:Payment['status'],metodo:Payment['metodo_pagamento']=null){const {error}=await supabase.rpc('atualizar_pagamento',{p_pagamento_id:id,p_status:status,p_metodo:metodo});if(error)throw error}
export async function refreshLatePayments(){const {error}=await supabase.rpc('atualizar_atrasados');if(error)throw error}
export async function myPayments(){const user=(await supabase.auth.getUser()).data.user;const {data,error}=await supabase.from('pagamentos').select('*').eq('user_id',user?.id).order('created_at',{ascending:false});if(error)throw error;return data as Payment[]}
export async function uploadReceipt(paymentId:string,file:File){const user=(await supabase.auth.getUser()).data.user;if(!user)throw new Error('Não autenticado');const ext=file.name.split('.').pop()?.toLowerCase()||'bin',path=`${user.id}/${paymentId}/${Date.now()}.${ext}`;const {error:uploadError}=await supabase.storage.from('comprovantes').upload(path,file,{contentType:file.type,upsert:false});if(uploadError)throw uploadError;const {error}=await supabase.rpc('enviar_comprovante',{p_pagamento_id:paymentId,p_path:path});if(error)throw error}
export async function receiptUrl(path:string){const {data,error}=await supabase.storage.from('comprovantes').createSignedUrl(path,300);if(error)throw error;return data.signedUrl}
export async function adminParticipant(peladaId: string, userId: string, action: 'add' | 'remove' | 'promote' | 'presente' | 'faltou') { const { error } = await supabase.rpc('admin_gerenciar_participante', { p_pelada_id: peladaId, p_user_id: userId, p_acao: action }); if (error) throw error }
export async function adminParticipantById(id:string,action:'remove'|'promote'|'demote'|'up'|'down'|'presente'|'faltou'|'linha'|'goleiro'){const {error}=await supabase.rpc('admin_gerenciar_participante_id',{p_participante_id:id,p_acao:action});if(error)throw error}
export async function adminAddPlayer(peladaId:string,jogadorId:string){const {error}=await supabase.rpc('admin_adicionar_jogador',{p_pelada_id:peladaId,p_jogador_id:jogadorId});if(error)throw error}
export async function ratePlayer(id:string,nota:number){const {error}=await supabase.rpc('admin_avaliar_jogador',{p_jogador_id:id,p_nota:nota});if(error)throw error}
export async function drawTeams(peladaId:string){const {data,error}=await supabase.from('pelada_times').select('*,player:jogadores!jogador_id(*)').eq('pelada_id',peladaId).order('time').order('ordem');if(error)throw error;return data as TeamMember[]}
export async function generateTeamDraw(peladaId:string){const {error}=await supabase.rpc('gerar_sorteio_times',{p_pelada_id:peladaId});if(error)throw error}
export async function swapTeamPlayers(peladaId:string,first:string,second:string){const {error}=await supabase.rpc('trocar_jogadores_sorteio',{p_pelada_id:peladaId,p_primeiro:first,p_segundo:second});if(error)throw error}
export async function publishTeamDraw(peladaId:string,published:boolean){const {error}=await supabase.rpc('publicar_sorteio_times',{p_pelada_id:peladaId,p_liberado:published});if(error)throw error}
export async function payments() { const { data, error } = await supabase.from('pagamentos').select('*, profile:profiles!user_id(*), player:jogadores!jogador_id(*)').order('created_at', { ascending: false }); if (error) throw error; return data as Payment[] }
export async function savePayment(values: Omit<Payment, 'id' | 'created_at' | 'profile'>) { const { error } = await supabase.from('pagamentos').insert(values); if (error) throw error }
export async function peladasHistory(){const {data,error}=await supabase.from('peladas').select('*').neq('status','cancelada').order('data',{ascending:false}).order('horario',{ascending:false}).limit(30);if(error)throw error;return data as Pelada[]}
export async function createMonthlyInvite(){const {data,error}=await supabase.rpc('criar_convite_mensalista');if(error)throw error;return data as string}
export async function deletePlayer(id:string){const {error}=await supabase.rpc('excluir_jogador',{p_id:id});if(error)throw error}
export async function expenses(){const {data,error}=await supabase.from('despesas').select('*,parcelas:despesa_parcelas(*)').order('created_at',{ascending:false});if(error)throw error;return data as Expense[]}
export async function createExpense(values:{descricao:string;data:string;parcelas:number;valor:number;valorTipo:'total'|'parcela'}){const {error}=await supabase.rpc('criar_despesa',{p_descricao:values.descricao,p_data:values.data,p_parcelas:values.parcelas,p_valor:values.valor,p_valor_tipo:values.valorTipo});if(error)throw error}
export async function updateExpenseInstallment(id:string,paga:boolean){const {error}=await supabase.rpc('atualizar_parcela_despesa',{p_id:id,p_paga:paga});if(error)throw error}
export async function deleteExpense(id:string){const {error}=await supabase.rpc('excluir_despesa',{p_id:id});if(error)throw error}
export async function setMonthlyExemption(id:string,isento:boolean){const {error}=await supabase.rpc('definir_isencao_mensalista',{p_jogador_id:id,p_isento:isento});if(error)throw error}
