import { lazy,Suspense,useState,type FormEvent } from 'react'
import { Empty,ErrorState,Spinner,Toast } from '../components/Ui'
import { useLoad } from '../hooks/useLoad'
import { activeSeries,adminParticipant,adminSummary,allProfiles,generateNextPelada,savePelada,saveSeries,setListPhase,setPlayerType } from '../lib/api'
import type { ListPhase,Pelada } from '../lib/database.types'

const FinancePanel=lazy(()=>import('../components/FinancePanel').then(module=>({default:module.FinancePanel})))

export function Admin(){const [tab,setTab]=useState<'pelada'|'jogadores'|'financeiro'>('pelada');const state=useLoad(async()=>{const [summary,profiles,series]=await Promise.all([adminSummary(),allProfiles(),activeSeries()]);return{summary,profiles,series}});const [toast,setToast]=useState('');if(state.loading)return <Spinner/>;if(state.error)return <ErrorState message={state.error} retry={state.reload}/>;const {summary,profiles,series}=state.data!;const feedback=(m:string)=>{setToast(m);setTimeout(()=>setToast(''),3500)};async function run(action:()=>Promise<unknown>,success:string){try{await action();feedback(success);await state.reload()}catch(err){feedback(err instanceof Error?err.message:'Não foi possível salvar.')}}
  async function recurrenceSubmit(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);await run(()=>saveSeries({id:series?.id,nome:'Pelada semanal',dia_semana:Number(f.get('dia')),horario:String(f.get('horario')),local:String(f.get('local')),limite_jogadores:20,antecedencia_mensalistas_horas:24,antecedencia_geral_horas:12,valor_mensalista:series?.valor_mensalista??0,valor_avulso:series?.valor_avulso??0,dia_vencimento:series?.dia_vencimento??10,ativa:true}),'Recorrência salva.')}
  async function gameSubmit(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);await run(()=>savePelada({id:summary.pelada?.id,data:String(f.get('data')),horario:String(f.get('horario')),local:String(f.get('local')),limite_jogadores:20,status:String(f.get('status')) as Pelada['status'],lista_aberta:false,fase_lista:summary.pelada?.fase_lista??'fechada'}),'Pelada salva.')}
  function copyList(){if(!summary.pelada)return;const active=summary.list.filter(p=>['confirmado','presente'].includes(p.status)),line=active.filter(p=>p.categoria!=='goleiro').slice(0,20),keepers=active.filter(p=>p.categoria==='goleiro'),waiting=summary.list.filter(p=>p.status==='espera'),rows=(items:typeof active)=>items.map((p,i)=>`${i+1}- ${p.profile?.apelido||p.profile?.nome}`).join('\n'),date=new Date(`${summary.pelada.data}T12:00`),tomorrow=date.toDateString()===new Date(Date.now()+86400000).toDateString()?'amanhã':date.toLocaleDateString('pt-BR');void navigator.clipboard.writeText(`Pelada ${tomorrow} ${summary.pelada.horario.slice(0,5)}\n\n${rows(line)}\n\nSuplentes\n${rows(waiting)}\n\nGoleiros\n${rows(keepers)}`).then(()=>feedback('Lista copiada.'))}
  return <section><p className="eyebrow">DIRETORIA</p><h1>Admin</h1><div className="admin-metrics"><div><b>{summary.list.filter(p=>p.status==='confirmado'&&p.categoria!=='goleiro').length}</b><span>Confirmados</span></div><div><b>{summary.list.filter(p=>p.status==='espera').length}</b><span>Suplentes</span></div><div><b>{summary.list.filter(p=>p.status==='confirmado'&&p.categoria==='goleiro').length}</b><span>Goleiros</span></div><div><b>{summary.mensalistas}</b><span>Mensalistas</span></div></div><div className="tabs">{(['pelada','jogadores','financeiro'] as const).map(x=><button className={tab===x?'active':''} onClick={()=>setTab(x)} key={x}>{x}</button>)}</div>
  {tab==='pelada'&&<><form className="panel form-grid" onSubmit={recurrenceSubmit}><h2>Recorrência semanal</h2><label>Dia<select name="dia" defaultValue={series?.dia_semana??5}><option value="0">Domingo</option><option value="1">Segunda</option><option value="2">Terça</option><option value="3">Quarta</option><option value="4">Quinta</option><option value="5">Sexta</option><option value="6">Sábado</option></select></label><label>Horário<input name="horario" type="time" defaultValue={series?.horario?.slice(0,5)??'20:30'} required/></label><label className="wide">Local<input name="local" defaultValue={series?.local??''} required/></label><button className="wide">SALVAR RECORRÊNCIA</button>{series&&<button type="button" className="wide secondary" onClick={()=>run(()=>generateNextPelada(series.id),'Próxima pelada gerada.')}>GERAR PRÓXIMA PELADA</button>}</form><form className="panel form-grid" onSubmit={gameSubmit}><h2>{summary.pelada?'Próxima pelada':'Ocorrência especial'}</h2><label>Data<input type="date" name="data" defaultValue={summary.pelada?.data} required/></label><label>Horário<input type="time" name="horario" defaultValue={summary.pelada?.horario?.slice(0,5)} required/></label><label className="wide">Local<input name="local" defaultValue={summary.pelada?.local} required/></label><label>Status<select name="status" defaultValue={summary.pelada?.status??'aberta'}><option value="aberta">Aberta</option><option value="encerrada">Encerrada</option><option value="cancelada">Cancelada</option></select></label><button className="wide">SALVAR OCORRÊNCIA</button></form>{summary.pelada&&<div className="panel"><h2>Lista: {summary.pelada.fase_lista}</h2><div className="phase-actions">{([['mensalistas','ABRIR MENSALISTAS'],['geral','ABRIR GERAL'],['fechada','FECHAR']] as [ListPhase,string][]).map(([phase,label])=><button className="mini" key={phase} onClick={()=>run(()=>setListPhase(summary.pelada!.id,phase),`Lista: ${phase}.`)}>{label}</button>)}<button className="mini" onClick={copyList}>COPIAR WHATSAPP</button></div>{summary.list.length?summary.list.map(p=><div className="admin-row" key={p.id}><span><b>{p.profile?.apelido||p.profile?.nome}</b><small>{p.categoria} • {p.status}</small></span><div>{p.status==='espera'&&<button className="mini" onClick={()=>run(()=>adminParticipant(summary.pelada!.id,p.user_id,'promote'),'Promovido.')}>Promover</button>}<button className="mini" onClick={()=>run(()=>adminParticipant(summary.pelada!.id,p.user_id,'presente'),'Presença marcada.')}>Presente</button><button className="mini danger" onClick={()=>run(()=>adminParticipant(summary.pelada!.id,p.user_id,'remove'),'Removido.')}>Remover</button></div></div>):<Empty title="Lista vazia"/>}</div>}</>}
  {tab==='jogadores'&&<div className="panel"><h2>Mensalistas e posições</h2>{profiles.map(p=><div className="admin-row" key={p.id}><span><b>{p.apelido||p.nome}</b><small>{p.tipo_jogador} • {p.posicao_lista}</small></span><div><button className="mini" onClick={()=>run(()=>setPlayerType(p.id,p.tipo_jogador==='mensalista'?'avulso':'mensalista',p.posicao_lista),'Tipo atualizado.')}>Mensalista/Avulso</button><button className="mini" onClick={()=>run(()=>setPlayerType(p.id,p.tipo_jogador,p.posicao_lista==='goleiro'?'linha':'goleiro'),'Posição atualizada.')}>Linha/Goleiro</button></div></div>)}</div>}{tab==='financeiro'&&<Suspense fallback={<Spinner/>}><FinancePanel/></Suspense>}<Toast message={toast}/></section>}
