import { useState, type FormEvent } from 'react'
import { Badge, Empty, ErrorState, Spinner, Toast } from '../components/Ui'
import { useLoad } from '../hooks/useLoad'
import { adminParticipant, adminSummary, allProfiles, payments, savePayment, savePelada, setListPhase, setPlayerType } from '../lib/api'
import type { ListPhase, Payment, Pelada } from '../lib/database.types'

export function Admin(){const [tab,setTab]=useState<'pelada'|'jogadores'|'pagamentos'>('pelada');const state=useLoad(async()=>{const [summary,profiles,money]=await Promise.all([adminSummary(),allProfiles(),payments()]);return{summary,profiles,money}});const [toast,setToast]=useState('');if(state.loading)return <Spinner/>;if(state.error)return <ErrorState message={state.error} retry={state.reload}/>;const {summary,profiles,money}=state.data!;
  const feedback=(m:string)=>{setToast(m);setTimeout(()=>setToast(''),3500)}
  async function run(action:()=>Promise<unknown>,success:string){try{await action();feedback(success);await state.reload()}catch(err){feedback(err instanceof Error?err.message:'Não foi possível salvar.')}}
  async function peladaSubmit(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);await run(()=>savePelada({id:summary.pelada?.id,data:String(f.get('data')),horario:String(f.get('horario')),local:String(f.get('local')),limite_jogadores:20,status:String(f.get('status')) as Pelada['status'],lista_aberta:false,fase_lista:summary.pelada?.fase_lista??'fechada'}),'Pelada salva.')}
  async function paymentSubmit(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);const value:Omit<Payment,'id'|'created_at'|'profile'>={user_id:String(f.get('user_id')),pelada_id:summary.pelada?.id??null,tipo:String(f.get('tipo')) as Payment['tipo'],valor:Number(f.get('valor')),status:String(f.get('status')) as Payment['status'],data_pagamento:String(f.get('data_pagamento')||'')||null,metodo_pagamento:String(f.get('metodo')) as Payment['metodo_pagamento'],referencia:String(f.get('referencia')||'')||null};await run(()=>savePayment(value),'Pagamento registrado.');e.currentTarget.reset()}
  function copyList(){if(!summary.pelada)return;const active=summary.list.filter(p=>['confirmado','presente'].includes(p.status));const line=active.filter(p=>p.categoria!=='goleiro').slice(0,20),keepers=active.filter(p=>p.categoria==='goleiro'),waiting=summary.list.filter(p=>p.status==='espera');const rows=(items:typeof active)=>items.map((p,i)=>`${i+1}- ${p.profile?.apelido||p.profile?.nome}`).join('\n');const tomorrow=new Date(`${summary.pelada.data}T12:00`).toDateString()===new Date(Date.now()+86400000).toDateString()?'amanhã':new Date(`${summary.pelada.data}T12:00`).toLocaleDateString('pt-BR');const text=`Pelada ${tomorrow} ${summary.pelada.horario.slice(0,5)}\n\n${rows(line)}\n\nSuplentes\n${rows(waiting)}\n\nGoleiros\n${rows(keepers)}`;void navigator.clipboard.writeText(text).then(()=>feedback('Lista copiada para o WhatsApp.'))}
  return <section><p className="eyebrow">DIRETORIA</p><h1>Admin</h1><div className="admin-metrics"><div><b>{summary.list.filter(p=>p.status==='confirmado'&&p.categoria!=='goleiro').length}</b><span>Confirmados</span></div><div><b>{summary.list.filter(p=>p.status==='espera').length}</b><span>Suplentes</span></div><div><b>{summary.list.filter(p=>p.status==='confirmado'&&p.categoria==='goleiro').length}</b><span>Goleiros</span></div><div><b>{summary.mensalistas}</b><span>Mensalistas</span></div></div><div className="tabs">{(['pelada','jogadores','pagamentos'] as const).map(x=><button className={tab===x?'active':''} onClick={()=>setTab(x)} key={x}>{x}</button>)}</div>
  {tab==='pelada'&&<><form className="panel form-grid" onSubmit={peladaSubmit}><h2>{summary.pelada?'Próxima pelada':'Criar pelada'}</h2><label>Data<input type="date" name="data" defaultValue={summary.pelada?.data} required/></label><label>Horário<input type="time" name="horario" defaultValue={summary.pelada?.horario?.slice(0,5)} required/></label><label className="wide">Local<input name="local" defaultValue={summary.pelada?.local} required/></label><label>Status<select name="status" defaultValue={summary.pelada?.status??'aberta'}><option value="aberta">Aberta</option><option value="encerrada">Encerrada</option><option value="cancelada">Cancelada</option></select></label><button className="wide">SALVAR PELADA</button></form>{summary.pelada&&<div className="panel"><h2>Fase da lista: {summary.pelada.fase_lista}</h2><div className="phase-actions">{([['mensalistas','ABRIR MENSALISTAS'],['geral','ABRIR GERAL'],['fechada','FECHAR']] as [ListPhase,string][]).map(([phase,label])=><button className="mini" key={phase} onClick={()=>run(()=>setListPhase(summary.pelada!.id,phase),`Lista: ${phase}.`)}>{label}</button>)}<button className="mini" onClick={copyList}>COPIAR WHATSAPP</button></div>{summary.list.length?summary.list.map(p=><div className="admin-row" key={p.id}><span><b>{p.profile?.apelido||p.profile?.nome}</b><small>{p.categoria} • {p.status}</small></span><div>{p.status==='espera'&&<button className="mini" onClick={()=>run(()=>adminParticipant(summary.pelada!.id,p.user_id,'promote'),'Jogador promovido.')}>Promover</button>}<button className="mini" onClick={()=>run(()=>adminParticipant(summary.pelada!.id,p.user_id,'presente'),'Presença marcada.')}>Presente</button><button className="mini danger" onClick={()=>run(()=>adminParticipant(summary.pelada!.id,p.user_id,'remove'),'Removido.')}>Remover</button></div></div>):<Empty title="Lista vazia"/>}</div>}</>}
  {tab==='jogadores'&&<div className="panel"><h2>Mensalistas e posições</h2>{profiles.map(p=><div className="admin-row" key={p.id}><span><b>{p.apelido||p.nome}</b><small>{p.tipo_jogador} • {p.posicao_lista}</small></span><div><button className="mini" onClick={()=>run(()=>setPlayerType(p.id,p.tipo_jogador==='mensalista'?'avulso':'mensalista',p.posicao_lista),'Tipo atualizado.')}>Mensalista/Avulso</button><button className="mini" onClick={()=>run(()=>setPlayerType(p.id,p.tipo_jogador,p.posicao_lista==='goleiro'?'linha':'goleiro'),'Posição atualizada.')}>Linha/Goleiro</button></div></div>)}</div>}
  {tab==='pagamentos'&&<><form className="panel form-grid" onSubmit={paymentSubmit}><h2>Registrar pagamento</h2><label className="wide">Jogador<select name="user_id" required><option value="">Selecione…</option>{profiles.map(p=><option value={p.id} key={p.id}>{p.nome}</option>)}</select></label><label>Tipo<select name="tipo"><option value="mensalidade">Mensalidade</option><option value="avulso">Avulso</option></select></label><label>Valor<input name="valor" type="number" min="0" step="0.01" required/></label><label>Status<select name="status"><option value="pago">Pago</option><option value="pendente">Pendente</option><option value="atrasado">Atrasado</option><option value="isento">Isento</option></select></label><label>Método<select name="metodo"><option value="pix">Pix</option><option value="dinheiro">Dinheiro</option><option value="outro">Outro</option></select></label><label>Data<input type="date" name="data_pagamento"/></label><label>Referência<input name="referencia"/></label><button className="wide">REGISTRAR</button></form><div className="panel"><h2>Registros</h2>{money.length?money.map(p=><div className="admin-row" key={p.id}><span><b>{p.profile?.apelido||p.profile?.nome}</b><small>{p.tipo} • R$ {Number(p.valor).toFixed(2)}</small></span><Badge>{p.status}</Badge></div>):<Empty title="Nenhum pagamento"/>}</div></>}<Toast message={toast}/></section>}
