import { ArrowRight, Calendar, MapPin, Users } from '../components/Icons'
import { Link } from 'react-router-dom'
import { useAuth } from '../auth/AuthContext'
import { Badge, Empty, ErrorState, Spinner, Toast } from '../components/Ui'
import { useLoad } from '../hooks/useLoad'
import { joinPelada, leavePelada, nextPelada, participants } from '../lib/api'
import { useState } from 'react'

export function Dashboard() { const { profile } = useAuth(); const state = useLoad(async () => { const game = await nextPelada(); return { game, list: game ? await participants(game.id) : [] } }, []); const [toast, setToast] = useState(''); const [busy, setBusy] = useState(false); if (state.loading) return <Spinner/>; if (state.error) return <ErrorState message={state.error} retry={state.reload}/>; const game = state.data?.game; if (!game) return <section><p className="eyebrow">BEM-VINDO, {profile?.apelido || profile?.nome}</p><h1>Próxima pelada</h1><Empty title="Nenhuma pelada marcada">Quando a diretoria marcar a próxima, ela aparece aqui.</Empty></section>; const list = state.data?.list ?? [], confirmed = list.filter(p => ['confirmado','presente'].includes(p.status)), mine = list.find(p => p.user_id === profile?.id), spots = Math.max(0, game.limite_jogadores - confirmed.length), waiting = list.filter(p => p.status === 'espera'); const waitingPosition = mine?.status === 'espera' ? waiting.findIndex(p => p.id === mine.id) + 1 : 0;
  const gameId = game.id
  async function act() { setBusy(true); try { if (mine) { await leavePelada(gameId); setToast('Você saiu da lista.') } else { const result = await joinPelada(gameId); setToast(result === 'espera' ? 'Lista cheia: você entrou na espera.' : 'Você está confirmado!') } await state.reload() } catch (err) { setToast(err instanceof Error ? err.message : 'Não foi possível atualizar a lista.') } finally { setBusy(false); setTimeout(() => setToast(''), 3500) } }
  return <section><p className="eyebrow">BEM-VINDO, {profile?.apelido || profile?.nome}</p><h1>Próxima pelada</h1><article className="game-card"><div className="game-card-top"><Badge>{game.lista_aberta ? 'LISTA ABERTA' : 'LISTA FECHADA'}</Badge><span>{new Date(`${game.data}T12:00`).toLocaleDateString('pt-BR', { weekday: 'short' }).toUpperCase()}</span></div><div className="date"><strong>{new Date(`${game.data}T12:00`).getDate()}</strong><div>{new Date(`${game.data}T12:00`).toLocaleDateString('pt-BR', { month: 'short' }).toUpperCase()}<small>{game.horario.slice(0,5)}</small></div></div><p><MapPin/> {game.local}</p><div className="progress"><span style={{width:`${Math.min(100, confirmed.length/game.limite_jogadores*100)}%`}}/></div><div className="capacity"><span><Users/> <b>{confirmed.length}/{game.limite_jogadores}</b> jogadores</span><b>{spots ? `${spots} vagas` : 'Lotada'}</b></div>{mine ? <div className="my-status"><b>{mine.status === 'espera' ? `Você é o ${waitingPosition}º da lista de espera` : '✓ VOCÊ ESTÁ CONFIRMADO'}</b><button className="secondary" onClick={act} disabled={busy}>SAIR DA LISTA</button></div> : <button onClick={act} disabled={busy || !game.lista_aberta}>{busy ? 'AGUARDE…' : game.lista_aberta ? 'ENTRAR NA LISTA' : 'LISTA FECHADA'} <ArrowRight/></button>}</article><Link className="section-link" to="/lista"><span><Calendar/> Ver lista completa</span><ArrowRight/></Link><Toast message={toast}/></section> }
