import { useEffect, useRef, useState } from "react";
import { useNavigate, useParams } from "react-router-dom";
import { useAuth } from "../auth/AuthContext";
import { useLoad } from "../hooks/useLoad";
import { finishRecording, recordingFragmentUrl, recordingFragments, recordingFullUrl, recordingHeartbeat, recordingSession, recordingTimeline, registerFullRecording, registerRecordingFragment, serverClockOffset, startRecording, uploadFullRecordingToR2, uploadRecordingToDrive } from "../lib/api";
import { matchDeviceId } from "../lib/matchOffline";
import { localRecordingFragments, markRecordingFragmentUploaded, saveRecordingFragment } from "../lib/recordingOffline";
import { supabase } from "../lib/supabase";
import { Empty, ErrorState, Spinner, Toast } from "../components/Ui";
import "./recording-camera.css";

const mime=()=>["video/webm;codecs=vp9,opus","video/webm","video/mp4"].find(item=>MediaRecorder.isTypeSupported(item))||"video/webm";
const clock=(ms:number)=>`${String(Math.floor(ms/60000)).padStart(2,"0")}:${String(Math.floor(ms%60000/1000)).padStart(2,"0")}`;
export function RecordingCamera(){const {peladaId=""}=useParams(),navigate=useNavigate(),{realProfile}=useAuth(),camera=useLoadCamera(peladaId),preview=useRef<HTMLVideoElement>(null),recorder=useRef<MediaRecorder>(),stream=useRef<MediaStream>(),sequence=useRef(0),chunkStart=useRef(0),full=useRef<Blob[]>([]),[sessionId,setSessionId]=useState(""),[capturing,setCapturing]=useState(false),[busy,setBusy]=useState(false),[playing,setPlaying]=useState(""),[toast,setToast]=useState("");const session=sessionId||camera.data?.session?.id||"",say=(text:string)=>{setToast(text);setTimeout(()=>setToast(""),4000)};
  async function uploadFragment(id:string,item:{id:string;sequence:number;startedAt:string;durationMs:number;mimeType:string;blob:Blob;sha256:string|null}){const path=`${peladaId}/${id}/trechos/${String(item.sequence+1).padStart(3,"0")}.${item.mimeType.includes("mp4")?"mp4":"webm"}`,{error}=await supabase.storage.from("pelada-gravacoes").upload(path,item.blob,{contentType:item.mimeType,upsert:true});if(error)throw error;const row=await registerRecordingFragment(id,item.sequence,item.startedAt,item.durationMs,path,item.mimeType,item.blob.size,item.sha256);void uploadRecordingToDrive(id,row.id).catch(()=>undefined);await markRecordingFragmentUploaded(item.id)}
  async function sync(id:string){if(!navigator.onLine)return;try{for(const item of(await localRecordingFragments(id)).filter(item=>!item.uploaded))await uploadFragment(id,item);await camera.reload()}catch{say("Trechos guardados neste aparelho para novo envio.")}}
  async function persist(id:string,blob:Blob,start:string,duration:number){const number=sequence.current++,item={id:`${id}-${number}`,sessionId:id,sequence:number,startedAt:start,durationMs:duration,mimeType:(blob.type||mime()).split(";")[0],blob,sha256:null,uploaded:false};full.current.push(blob);await saveRecordingFragment(item);void sync(id)}
  async function start(){if(!peladaId||!navigator.mediaDevices?.getUserMedia){say("Câmera indisponível neste navegador.");return}setBusy(true);try{const media=await navigator.mediaDevices.getUserMedia({video:{facingMode:{ideal:"environment"},width:{ideal:1920},height:{ideal:1080}},audio:true}),offset=await serverClockOffset().catch(()=>0),now=new Date(Date.now()+offset).toISOString(),created=await startRecording(peladaId,`${matchDeviceId()}-camera`,now,offset);stream.current=media;sequence.current=0;full.current=[];chunkStart.current=Date.now();if(preview.current){preview.current.srcObject=media;await preview.current.play().catch(()=>undefined)}const next=new MediaRecorder(media,{mimeType:mime()});next.ondataavailable=event=>{if(event.data.size){const end=Date.now(),begin=chunkStart.current;chunkStart.current=end;void persist(created.id,event.data,new Date(begin+offset).toISOString(),end-begin)}};next.start(5000);recorder.current=next;setSessionId(created.id);setCapturing(true);say("Gravação iniciada.")}catch(error){say(error instanceof Error?error.message:"Não foi possível iniciar a câmera.")}finally{setBusy(false)}}
  async function stop(){if(!session||!recorder.current)return;setBusy(true);try{const stopped=new Promise<void>(resolve=>recorder.current!.addEventListener("stop",()=>resolve(),{once:true}));recorder.current.stop();await stopped;stream.current?.getTracks().forEach(track=>track.stop());const blob=new Blob(full.current,{type:mime()}),path=`${peladaId}/${session}/completo.${blob.type.includes("mp4")?"mp4":"webm"}`;if(blob.size){const{error}=await supabase.storage.from("pelada-gravacoes").upload(path,blob,{contentType:blob.type,upsert:true});if(error)throw error;await registerFullRecording(session,path,blob.type,blob.size);await uploadFullRecordingToR2(session)}await finishRecording(session,new Date().toISOString());await sync(session);await camera.reload();setCapturing(false);say("Vídeo completo e trechos salvos.")}catch(error){say(error instanceof Error?error.message:"Falha ao finalizar.")}finally{setBusy(false)}}
  // eslint-disable-next-line react-hooks/exhaustive-deps
  useEffect(()=>{if(!session)return;void sync(session);const timer=setInterval(()=>void recordingHeartbeat(session).catch(()=>undefined),20000);return()=>clearInterval(timer)},[session]);
  if(realProfile?.role!=="superadmin")return <ErrorState message="A gravação é exclusiva do superadmin."/>;if(camera.loading)return <Spinner/>;if(camera.error)return <ErrorState message={camera.error} retry={camera.reload}/>;if(!peladaId)return <Empty title="Pelada não encontrada"/>;const fragments=camera.data?.fragments??[],complete=camera.data?.session?.full_storage_path;return <section className="recording-camera"><header><button className="link" onClick={()=>navigate(-1)}>← VOLTAR</button><b className={capturing?"rec-on":"rec-off"}>{capturing?"● REC":"○ CÂMERA"}</b></header><p className="eyebrow">MODO CÂMERA</p><h1>Gravação da pelada</h1><video className="camera-preview" ref={preview} autoPlay muted playsInline/>{capturing?<button className="danger full" disabled={busy} onClick={()=>void stop()}>■ FINALIZAR GRAVAÇÃO</button>:<button className="full" disabled={busy} onClick={()=>void start()}>● INICIAR GRAVAÇÃO</button>}<small className="recording-note">Trechos de 5 segundos protegem contra quedas. Ao finalizar, o vídeo completo também é salvo.</small><section className="panel recording-timeline"><h2>Vídeos gravados</h2>{playing&&<video className="recording-playback" controls autoPlay playsInline src={playing}/>} {complete&&<article><span><b>Vídeo completo</b><small>{camera.data?.session?.full_byte_size?`${(camera.data.session.full_byte_size/1024/1024).toFixed(1)} MB`:"Pronto para assistir"}</small></span><button className="mini secondary" onClick={()=>void recordingFullUrl(session).then(setPlaying).catch(error=>say(error instanceof Error?error.message:"Vídeo indisponível."))}>ASSISTIR</button></article>}{fragments.map(fragment=><article key={fragment.id}><span><b>Trecho {fragment.sequence_number+1}</b><small>{clock(fragment.duration_ms)} • {(fragment.byte_size/1024/1024).toFixed(1)} MB</small></span><button className="mini secondary" onClick={()=>void recordingFragmentUrl(fragment.storage_path).then(setPlaying).catch(error=>say(error instanceof Error?error.message:"Vídeo indisponível."))}>ASSISTIR</button></article>)}</section><section className="panel recording-timeline"><h2>Eventos por partida</h2>{groupEvents(camera.data?.events??[]).map(([partida,events])=><div key={partida}><b>Partida {partida}</b>{events.map(event=><article key={event.id}><span><b>{event.type}</b><small>{clock(event.recording_offset_ms??0)}</small></span></article>)}</div>)}</section><Toast message={toast}/></section>}
function groupEvents(events:Awaited<ReturnType<typeof recordingTimeline>>){const groups=new Map<string,typeof events>();for(const event of events){const key=String(event.match?.sequence_number??0),list=groups.get(key)??[];list.push(event);groups.set(key,list)}return[...groups.entries()]}
function useLoadCamera(peladaId:string){return useLoad(async()=>{const session=await recordingSession(peladaId,`${matchDeviceId()}-camera`);if(!session)return{session:null,fragments:[],events:[]};const[fragments,events]=await Promise.all([recordingFragments(session.id),recordingTimeline(session.id)]);return{session,fragments,events}},peladaId)}
