import { useState, type FormEvent } from 'react'
import { Badge, Empty, ErrorState, Spinner, Toast } from '../components/Ui'
import { useLoad } from '../hooks/useLoad'
import { allProfiles, createUser } from '../lib/api'
import type { ListPosition, PlayerType, Role } from '../lib/database.types'

export function SuperAdmin() { const state=useLoad(allProfiles); const [toast,setToast]=useState(''); const [busy,setBusy]=useState(false); if(state.loading)return <Spinner/>; if(state.error)return <ErrorState message={state.error} retry={state.reload}/>;
  async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();setBusy(true);const f=new FormData(e.currentTarget);try{await createUser({nome:String(f.get('nome')),email:String(f.get('email')),role:String(f.get('role')) as Role,tipo_jogador:String(f.get('tipo')) as PlayerType,posicao_lista:String(f.get('posicao')) as ListPosition});setToast('Convite enviado e usuário criado.');e.currentTarget.reset();await state.reload()}catch(err){setToast(err instanceof Error?err.message:'Falha ao criar usuário.')}finally{setBusy(false);setTimeout(()=>setToast(''),4000)}}
  return <section><p className="eyebrow">CONTROLE DE ACESSO</p><h1>Superadmin</h1><form className="panel form-grid" onSubmit={submit}><h2>Convidar usuário</h2><label>Nome<input name="nome" minLength={2} required/></label><label>E-mail<input name="email" type="email" required/></label><label>Permissão<select name="role"><option value="user">Usuário</option><option value="admin">Admin</option><option value="superadmin">Superadmin</option></select></label><label>Tipo<select name="tipo"><option value="avulso">Avulso</option><option value="mensalista">Mensalista</option></select></label><label>Lista<select name="posicao"><option value="linha">Linha</option><option value="goleiro">Goleiro</option></select></label><button className="wide" disabled={busy}>{busy?'CRIANDO…':'CRIAR E ENVIAR CONVITE'}</button></form><div className="panel"><h2>Usuários</h2>{state.data?.length?state.data.map(p=><div className="admin-row" key={p.id}><span><b>{p.apelido||p.nome}</b><small>{p.tipo_jogador} • {p.posicao_lista}</small></span><Badge tone={p.role==='superadmin'?'yellow':p.role==='admin'?'green':'gray'}>{p.role.toUpperCase()}</Badge></div>):<Empty title="Nenhum usuário"/>}</div><Toast message={toast}/></section> }
