import "./admin-receipt-inbox.css";
import { useState } from "react";
import { receiptUrl, updatePayment } from "../lib/api";
import type { Payment } from "../lib/database.types";
import { Badge, Toast } from "./Ui";

const money = new Intl.NumberFormat("pt-BR", { style: "currency", currency: "BRL" });
type Props = { payments: Payment[]; onChanged: () => Promise<void> };
const playerName = (payment: Payment) => payment.player?.apelido || payment.player?.nome || payment.profile?.apelido || payment.profile?.nome || "Jogador";
export function AdminReceiptInbox({ payments, onChanged }: Props) { const [toast, setToast] = useState(""); const feedback = (message: string) => { setToast(message); setTimeout(() => setToast(""), 3500); }; if (!payments.length) return null; async function view(payment: Payment) { if (!payment.comprovante_path) return; try { window.open(await receiptUrl(payment.comprovante_path), "_blank", "noopener,noreferrer"); } catch (error) { feedback(error instanceof Error ? error.message : "Não foi possível abrir o comprovante."); } } async function settle(payment: Payment) { try { await updatePayment(payment.id, "pago", "pix"); await onChanged(); feedback("Pagamento quitado."); } catch (error) { feedback(error instanceof Error ? error.message : "Não foi possível quitar o pagamento."); } } return <section className="panel admin-receipt-inbox"><div className="admin-receipt-title"><h2>Comprovantes recebidos</h2><Badge>{payments.length} para conferir</Badge></div><p>Confira o arquivo e quite o pagamento diretamente por aqui.</p>{payments.slice(0, 5).map((payment) => <div className="admin-row" key={payment.id}><span><b>{playerName(payment)}</b><small>{payment.referencia || payment.tipo} • {money.format(Number(payment.valor))}{payment.comprovante_enviado_em ? ` • enviado ${new Date(payment.comprovante_enviado_em).toLocaleString("pt-BR")}` : ""}</small></span><div><button className="mini secondary" onClick={() => void view(payment)}>VISUALIZAR</button><button className="mini" onClick={() => void settle(payment)}>QUITAR</button></div></div>)}{payments.length > 5 && <small className="admin-receipt-more">Há mais {payments.length - 5} comprovante{payments.length - 5 === 1 ? "" : "s"} no Financeiro.</small>}<Toast message={toast} /></section>; }
