import {useState,type FormEvent} from 'react'
import {useLoad} from '../hooks/useLoad'
import {createExpense,deleteExpense,expenses,payments,updateExpenseInstallment} from '../lib/api'
import type {Expense,Payment} from '../lib/database.types'
import {Badge,Empty,ErrorState,Spinner,Toast} from './Ui'

const money=new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL'})
export function calculateFinanceSummary(income:Payment[],costs:Expense[]){const received=income.filter(x=>x.status==='pago').reduce((sum,x)=>sum+Number(x.valor),0),expectedIncome=income.filter(x=>x.status!=='isento').reduce((sum,x)=>sum+Number(x.valor),0),installments=costs.flatMap(x=>x.parcelas),paidCosts=installments.filter(x=>x.paga).reduce((sum,x)=>sum+Number(x.valor),0),futureCosts=installments.filter(x=>!x.paga).reduce((sum,x)=>sum+Number(x.valor),0);return{balance:received-paidCosts,expectedBalance:expectedIncome-paidCosts-futureCosts,futureCosts}}

export function ExpensePanel(){const state=useLoad(async()=>{const [income,costs]=await Promise.all([payments(),expenses()]);return{income,costs}}),[toast,setToast]=useState(''),[preview,setPreview]=useState({parcelas:1,valor:0,tipo:'total'});if(state.loading)return <Spinner/>;if(state.error)return <ErrorState message={state.error} retry={state.reload}/>;const {income,costs}=state.data!,summary=calculateFinanceSummary(income,costs),parcelValue=preview.tipo==='total'?preview.valor/Math.max(1,preview.parcelas):preview.valor,totalValue=preview.tipo==='parcela'?preview.valor*preview.parcelas:preview.valor;const feedback=(message:string)=>{setToast(message);setTimeout(()=>setToast(''),3500)};async function run(action:()=>Promise<unknown>,message:string){try{await action();feedback(message);await state.reload()}catch(err){feedback(err instanceof Error?err.message:'Não foi possível concluir.')}}async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();const form=e.currentTarget,f=new FormData(form);await run(()=>createExpense({descricao:String(f.get('descricao')),data:String(f.get('data')),parcelas:Number(f.get('parcelas')),valor:Number(f.get('valor')),valorTipo:String(f.get('valor_tipo')) as 'total'|'parcela'}),'Gasto cadastrado.');form.reset();setPreview({parcelas:1,valor:0,tipo:'total'})}
  return <div className="expenses"><div className="finance-kpis"><div><span>Saldo atual</span><b>{money.format(summary.balance)}</b></div><div><span>Saldo previsto</span><b>{money.format(summary.expectedBalance)}</b></div><div><span>Gastos previstos</span><b>{money.format(summary.futureCosts)}</b></div></div><form className="panel form-grid" onSubmit={submit} onChange={e=>{const f=new FormData(e.currentTarget);setPreview({parcelas:Number(f.get('parcelas')||1),valor:Number(f.get('valor')||0),tipo:String(f.get('valor_tipo')||'total')})}}><h2>Cadastrar gasto</h2><label className="wide">Descrição<input name="descricao" minLength={2} required placeholder="Ex.: aluguel do campo"/></label><label>Primeiro vencimento<input name="data" type="date" required/></label><label>Parcelas<input name="parcelas" type="number" min="1" max="120" defaultValue="1" required/></label><label>Valor informado<select name="valor_tipo" defaultValue="total"><option value="total">Valor total</option><option value="parcela">Valor da parcela</option></select></label><label>Valor<input name="valor" type="number" min="0.01" step="0.01" required/></label><div className="wide finance-preview"><span>Total: <b>{money.format(totalValue||0)}</b></span><span>{preview.parcelas}x de <b>{money.format(parcelValue||0)}</b></span></div><button className="wide">CADASTRAR GASTO</button></form><div className="panel"><h2>Despesas e parcelas</h2>{costs.length?costs.map(cost=><div className="expense" key={cost.id}><div className="expense-head"><span><b>{cost.descricao}</b><small>{cost.numero_parcelas}x • total {money.format(Number(cost.valor_total))}</small></span><button className="mini danger" onClick={()=>confirm(`Excluir ${cost.descricao}?`)&&run(()=>deleteExpense(cost.id),'Gasto excluído.')}>EXCLUIR</button></div>{[...cost.parcelas].sort((a,b)=>a.numero-b.numero).map(item=><div className="payment-row" key={item.id}><div><b>Parcela {item.numero}/{cost.numero_parcelas}</b><small>Vence {new Date(`${item.data_vencimento}T12:00`).toLocaleDateString('pt-BR')} • {money.format(Number(item.valor))}</small></div><div><Badge tone={item.paga?'green':'yellow'}>{item.paga?'paga':'prevista'}</Badge><button className={`mini ${item.paga?'secondary':''}`} onClick={()=>run(()=>updateExpenseInstallment(item.id,!item.paga),item.paga?'Parcela reaberta.':'Parcela paga.')}>{item.paga?'REABRIR':'MARCAR PAGA'}</button></div></div>)}</div>):<Empty title="Nenhum gasto cadastrado"/>}</div><Toast message={toast}/></div>}
