import { useState,type FormEvent } from 'react'
import { Bar,BarChart,ResponsiveContainer,Tooltip,XAxis } from 'recharts'
import { useLoad } from '../hooks/useLoad'
import { activeSeries,generateCasualCharges,generateMonthlyCharges,nextPelada,payments,receiptUrl,refreshLatePayments,saveFinanceConfig,updatePayment } from '../lib/api'
import type { Payment,PaymentStatus } from '../lib/database.types'
import { Badge,Empty,ErrorState,Spinner,Toast } from './Ui'

const money=new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL'})
export function FinancePanel(){
  const state=useLoad(async()=>{await refreshLatePayments();const [series,items,game]=await Promise.all([activeSeries(),payments(),nextPelada()]);return{series,items,game}})
  const [toast,setToast]=useState(''),[filter,setFilter]=useState<'todos'|PaymentStatus>('todos')
  if(state.loading)return <Spinner/>;if(state.error)return <ErrorState message={state.error} retry={state.reload}/>
  const {series,items,game}=state.data!,feedback=(m:string)=>{setToast(m);setTimeout(()=>setToast(''),3500)}
  async function run(action:()=>Promise<unknown>,message:string){try{await action();feedback(message);await state.reload()}catch(err){feedback(err instanceof Error?err.message:'Não foi possível concluir.')}}
  async function config(e:FormEvent<HTMLFormElement>){e.preventDefault();if(!series)return;const f=new FormData(e.currentTarget);await run(()=>saveFinanceConfig(series.id,{valor_mensalista:Number(f.get('mensal')),valor_avulso:Number(f.get('avulso')),dia_vencimento:Number(f.get('vencimento')),chave_pix:String(f.get('pix'))}),'Configuração atualizada.')}
  async function proof(payment:Payment){if(!payment.comprovante_path)return;try{open(await receiptUrl(payment.comprovante_path),'_blank','noopener,noreferrer')}catch(err){feedback(err instanceof Error?err.message:'Falha ao abrir comprovante.')}}
  if(!series)return <Empty title="Configure a recorrência da pelada primeiro"/>
  const received=items.filter(p=>p.status==='pago').reduce((s,p)=>s+Number(p.valor),0),openValue=items.filter(p=>['pendente','atrasado'].includes(p.status)).reduce((s,p)=>s+Number(p.valor),0),expected=items.filter(p=>p.status!=='isento').reduce((s,p)=>s+Number(p.valor),0),groups=new Map<string,{name:string;recebido:number;aberto:number}>()
  for(const p of items){const key=p.competencia?.slice(0,7)||p.created_at.slice(0,7),name=new Date(`${key}-02T12:00`).toLocaleDateString('pt-BR',{month:'short'}),row=groups.get(key)||{name,recebido:0,aberto:0};if(p.status==='pago')row.recebido+=Number(p.valor);else if(p.status!=='isento')row.aberto+=Number(p.valor);groups.set(key,row)}
  const chart=[...groups.entries()].sort(([a],[b])=>a.localeCompare(b)).slice(-6).map(([,v])=>v),visible=filter==='todos'?items:items.filter(p=>p.status===filter)
  return <div className="finance"><div className="finance-hero"><p>RECEBIDO</p><strong>{money.format(received)}</strong><span>de {money.format(expected)} previstos</span></div><div className="finance-kpis"><div><span>Em aberto</span><b>{money.format(openValue)}</b></div><div><span>Atrasados</span><b>{items.filter(p=>p.status==='atrasado').length}</b></div><div><span>Comprovantes</span><b>{items.filter(p=>p.comprovante_path&&p.status!=='pago').length}</b></div></div>
  {chart.length>0&&<div className="finance-chart"><ResponsiveContainer width="100%" height={190}><BarChart data={chart}><XAxis dataKey="name" axisLine={false} tickLine={false} tick={{fill:'#989c91',fontSize:11}}/><Tooltip formatter={value=>money.format(Number(value))} contentStyle={{background:'#151713',border:'1px solid #34372e'}}/><Bar dataKey="recebido" name="Recebido" fill="#ffd500" radius={[4,4,0,0]}/><Bar dataKey="aberto" name="Em aberto" fill="#55584f" radius={[4,4,0,0]}/></BarChart></ResponsiveContainer></div>}
  <form className="panel form-grid" onSubmit={config}><h2>Cobranças</h2><label>Mensalidade<input name="mensal" type="number" min="0" step="0.01" defaultValue={series.valor_mensalista}/></label><label>Avulso/pelada<input name="avulso" type="number" min="0" step="0.01" defaultValue={series.valor_avulso}/></label><label>Vencimento<input name="vencimento" type="number" min="1" max="28" defaultValue={series.dia_vencimento}/></label><label className="wide">Chave PIX<input name="pix" defaultValue={series.chave_pix}/></label><button className="wide">SALVAR CONFIGURAÇÃO</button></form>
  <div className="finance-actions"><button onClick={()=>run(()=>generateMonthlyCharges(series.id,new Date().toISOString().slice(0,10)),'Mensalidades geradas.')}>GERAR MÊS ATUAL</button><button className="secondary" disabled={!game} onClick={()=>game&&run(()=>generateCasualCharges(game.id,series.id),'Avulsos cobrados.')}>COBRAR AVULSOS</button></div><div className="filter-pills">{(['todos','pendente','atrasado','pago','isento'] as const).map(x=><button className={filter===x?'active':''} onClick={()=>setFilter(x)} key={x}>{x}</button>)}</div>
  <div className="panel"><h2>Lançamentos</h2>{visible.length?visible.map(p=><div className="payment-row" key={p.id}><div><b>{p.player?.apelido||p.player?.nome||p.profile?.apelido||p.profile?.nome}</b><small>{p.referencia||p.tipo} • {money.format(Number(p.valor))}{p.data_vencimento?` • vence ${new Date(`${p.data_vencimento}T12:00`).toLocaleDateString('pt-BR')}`:''}</small></div><div><Badge tone={p.status==='pago'?'green':p.status==='atrasado'?'red':p.status==='isento'?'gray':'yellow'}>{p.status}</Badge>{p.comprovante_path&&p.status!=='pago'&&<button className="mini secondary" onClick={()=>proof(p)}>VER COMPROVANTE</button>}{p.status!=='pago'&&<button className="mini" onClick={()=>run(()=>updatePayment(p.id,'pago','pix'),'Pagamento validado.')}>VALIDAR PIX</button>}{!['isento','pago'].includes(p.status)&&<button className="mini secondary" onClick={()=>run(()=>updatePayment(p.id,'isento'),'Isentado.')}>ISENTO</button>}</div></div>):<Empty title="Nenhum lançamento"/>}</div><Toast message={toast}/></div>
}
