import {AppBar,BottomNavigation,BottomNavigationAction,Box,IconButton,Paper,Stack,Toolbar} from '@mui/material'
import {NavLink,Outlet,useLocation} from 'react-router-dom'
import {useAuth} from '../auth/AuthContext'
import {Finance,ListOrdered,PlayerCardIcon,Shield,Trophy,UserRound,Users} from './Icons'
import {ListReminder} from './ListReminder'
import {NotificationDelivery} from './NotificationDelivery'

const links=[{to:'/lista',label:'Lista',icon:ListOrdered},{to:'/cartinha',label:'Cartinha',icon:PlayerCardIcon},{to:'/ranking',label:'Ranking',icon:Trophy},{to:'/financeiro',label:'Financeiro',icon:Finance}]
export function Layout(){const {profile,realProfile}=useAuth(),location=useLocation(),admin=profile?.role==='admin'||profile?.role==='superadmin',items=[...links,...(admin?[{to:'/admin',label:'Admin',icon:Shield}]:[])];return <Box sx={{pb:'calc(76px + env(safe-area-inset-bottom))'}}><AppBar position="sticky" color="transparent" elevation={0} sx={{borderBottom:'1px solid',borderColor:'divider',backdropFilter:'blur(18px)',WebkitBackdropFilter:'blur(18px)'}}><Toolbar sx={{minHeight:'64px!important',justifyContent:'space-between',maxWidth:900,width:'100%',mx:'auto'}}><NavLink to="/" aria-label="Ir para o início"><img className="header-logo" src="/logo.png" alt="Pelada dos Sub"/></NavLink><Stack direction="row" spacing={.5}><IconButton component={NavLink} to="/perfil" color={location.pathname==='/perfil'?'primary':'inherit'} title="Perfil" aria-label="Perfil"><UserRound/></IconButton>{realProfile?.role==='superadmin'&&<IconButton component={NavLink} to="/superadmin" color={location.pathname==='/superadmin'?'primary':'inherit'} title="Usuários" aria-label="Usuários"><Users/></IconButton>}</Stack></Toolbar></AppBar><NotificationDelivery/><ListReminder/><main><Outlet/></main><Paper component="nav" elevation={10} sx={{position:'fixed',zIndex:20,bottom:0,left:0,right:0,pb:'env(safe-area-inset-bottom)',bgcolor:'rgba(13,15,12,.94)',backdropFilter:'blur(18px)',WebkitBackdropFilter:'blur(18px)'}}><BottomNavigation showLabels value={items.some(x=>x.to===location.pathname)?location.pathname:false} sx={{height:66,bgcolor:'transparent','& .MuiBottomNavigationAction-root':{minWidth:0,paddingInline:.25},'& .MuiBottomNavigationAction-label':{fontSize:'9px!important'}}}>{items.map(({to,label,icon:Icon})=><BottomNavigationAction component={NavLink} to={to} key={to} value={to} label={label} icon={<Icon/>}/>)}</BottomNavigation></Paper></Box>}
