import { useEffect, useState } from "react";
import { deleteMatchCardImage, generateMatchCard, matchAwards, matchCardImageUrl, matchCards, participants, peladasHistory, updateMatchCard, uploadMatchCardImage } from "../lib/api";
import { useLoad } from "../hooks/useLoad";
import type { MatchCard, Participant, Pelada, VoteCategory } from "../lib/database.types";
import { ErrorState, Spinner, Toast } from "./Ui";
import "./match-cards.css";

const categories:[VoteCategory,string][]=[["destaque","Destaque"],["surpresa","Surpresa"],["negativo","Quem quebrou mais"]];
export function MatchAwardCard({card,game}:{card:MatchCard;game?:Pelada}){return <article className={`match-card match-card-${card.categoria}`}>{card.snapshot_foto_url?<img src={card.snapshot_foto_url} alt=""/>:<div className="match-card-avatar">{card.snapshot_nome[0]}</div>}<small>PELADA DOS SUB</small><h2>{card.titulo}</h2><strong>{card.snapshot_nome}</strong><span>{card.snapshot_time||"Time não informado"} • {card.snapshot_gols} {card.snapshot_gols===1?"gol":"gols"}</span>{game&&<time>{new Date(`${game.data}T12:00`).toLocaleDateString("pt-BR")} • {game.local}</time>}</article>}

export function MatchCardsManager(){
  const [gameId,setGameId]=useState(""),[choices,setChoices]=useState<Partial<Record<VoteCategory,string>>>({}),[toast,setToast]=useState("");
  const state=useLoad(async()=>{const games=await peladasHistory(),id=gameId||games[0]?.id||"";if(!id)return{games,list:[],awards:[],cards:[]};const[list,awards,cards]=await Promise.all([participants(id),matchAwards(id),matchCards(id)]);return{games,list,awards,cards}},gameId);
  if(state.loading)return <Spinner/>;if(state.error)return <ErrorState message={state.error} retry={state.reload}/>;const{games,list,awards,cards}=state.data!,id=gameId||games[0]?.id||"",game=games.find(g=>g.id===id);
  const name=(item:Participant)=>item.player?.profile?.apelido||item.player?.apelido||item.player?.nome||"?";
  async function run(action:()=>Promise<unknown>,message:string){try{await action();setToast(message);await state.reload()}catch(error){setToast(error instanceof Error?error.message:"Não foi possível concluir.")}finally{setTimeout(()=>setToast(""),3500)}}
  return <section className="cards-manager"><header><span><p className="eyebrow">CARDS DA PELADA</p><h2>Gerar e publicar</h2></span><select value={id} onChange={e=>setGameId(e.target.value)}>{games.map(g=><option value={g.id} key={g.id}>{new Date(`${g.data}T12:00`).toLocaleDateString("pt-BR")} • {g.local}</option>)}</select></header>{categories.map(([category,title])=>{const results=awards.filter(a=>a.categoria===category),top=results[0]?.votos??0,winners=results.filter(a=>a.votos===top&&top>0),choice=choices[category]||winners[0]?.jogador_id||"",card=cards.find(c=>c.categoria===category);return <article className="card-manager-row" key={category}><div><h3>{title}</h3>{!winners.length?<small>Sem votos. Escolha um participante.</small>:winners.length>1?<small>Empate com {top} votos. Escolha o vencedor.</small>:<small>{winners[0].apelido||winners[0].nome} • {top} {top===1?"voto":"votos"}</small>}<select value={choice} onChange={e=>setChoices(old=>({...old,[category]:e.target.value}))}><option value="">Escolha…</option>{list.filter(p=>p.status!=="cancelado"&&p.status!=="faltou").sort((a,b)=>name(a).localeCompare(name(b),"pt-BR")).map(p=><option value={p.jogador_id} key={p.id}>{name(p)}</option>)}</select><button disabled={!choice} onClick={()=>void run(async()=>{await generateMatchCard(id,category,choice);if(card?.imagem_path)await deleteMatchCardImage(card.imagem_path)},"Card gerado como rascunho.")}>Gerar rascunho</button></div>{card&&<div className="card-manager-preview">{card.imagem_path?<img src={matchCardImageUrl(card.imagem_path)} alt={card.titulo}/>:<MatchAwardCard card={card} game={game}/>}<nav><label className="upload-card">Substituir imagem<input type="file" accept="image/jpeg,image/png,image/webp" onChange={e=>{const file=e.target.files?.[0];if(file)void run(async()=>{const old=card.imagem_path,path=await uploadMatchCardImage(card,file);await updateMatchCard(card,false,path);if(old)await deleteMatchCardImage(old)},"Imagem substituída em rascunho.")}}/></label>{card.imagem_path&&<button className="secondary" onClick={()=>void run(async()=>{await updateMatchCard(card,false,null);await deleteMatchCardImage(card.imagem_path!)},"Card gerado restaurado.")}>Usar card gerado</button>}<button onClick={()=>void run(()=>updateMatchCard(card,!card.liberado),card.liberado?"Card ocultado.":"Card liberado.")}>{card.liberado?"Ocultar":"Liberar"}</button></nav><b className={card.liberado?"published":"draft"}>{card.liberado?"LIBERADO":"RASCUNHO"}</b></div>}</article>})}<Toast message={toast}/></section>
}

export function MatchCardsGallery({game}:{game?:Pelada}){const [open,setOpen]=useState<MatchCard|null>(null);const state=useLoad(()=>game?matchCards(game.id):Promise.resolve([]),game?.id);useEffect(()=>{if(!open)return;const close=(e:KeyboardEvent)=>{if(e.key==="Escape")setOpen(null)};addEventListener("keydown",close);history.pushState({card:true},"");const pop=()=>setOpen(null);addEventListener("popstate",pop,{once:true});return()=>removeEventListener("keydown",close)},[open]);if(state.loading)return null;const cards=(state.data??[]).filter(c=>c.liberado);if(!cards.length)return null;return <section className="cards-gallery"><p className="eyebrow">CARDS DA PELADA</p><h2>Veja os vencedores</h2><div>{cards.map(card=><button key={card.id} onClick={()=>setOpen(card)}>{card.titulo}<small>Visualizar card</small></button>)}</div>{open&&<aside className="card-viewer" role="dialog" aria-modal="true"><button aria-label="Fechar" onClick={()=>{history.back();setOpen(null)}}>×</button>{open.imagem_path?<img src={matchCardImageUrl(open.imagem_path)} alt={open.titulo}/>:<MatchAwardCard card={open} game={game}/>}</aside>}</section>}
