import { useState } from "react";
import { allManagedPlayers, allPeladasHistory, controlPlayer, participants } from "../lib/api";
import { useLoad } from "../hooks/useLoad";
import { Empty, ErrorState, Spinner, Toast } from "./Ui";
import type { Participant, Player } from "../lib/database.types";
import "./player-control-panel.css";

export function PlayerControlPanel(){
  const [filter,setFilter]=useState<"mensalista"|"avulso">("mensalista"),[toast,setToast]=useState("");
  const state=useLoad(async()=>{const[players,games]=await Promise.all([allManagedPlayers(),allPeladasHistory()]),lists=Object.fromEntries(await Promise.all(games.map(async game=>[game.id,await participants(game.id)] as const))) as Record<string,Participant[]>;return{players,games,lists}});
  if(state.loading)return <Spinner/>;if(state.error)return <ErrorState message={state.error} retry={state.reload}/>;
  const {players,lists}=state.data!,history=Object.values(lists).flat(),rows=players.filter(player=>player.tipo===filter).sort((a,b)=>(a.apelido||a.nome).localeCompare(b.apelido||b.nome,"pt-BR",{sensitivity:"base"}));
  async function update(player:Player,changes:Partial<Pick<Player,"tipo"|"ativo"|"confirmacao_bloqueada">>,message:string){try{await controlPlayer(player.id,changes.tipo??player.tipo,changes.ativo??player.ativo,changes.confirmacao_bloqueada??Boolean(player.confirmacao_bloqueada));setToast(message);await state.reload()}catch(error){setToast(error&&typeof error==="object"&&"message" in error?String(error.message):"Não foi possível atualizar.")}finally{setTimeout(()=>setToast(""),3500)}}
  return <section className="player-control"><header><span><h2>Histórico individual</h2><small>Totais de todas as peladas</small></span><nav><button className={filter==="mensalista"?"active":""} onClick={()=>setFilter("mensalista")}>Mensalistas</button><button className={filter==="avulso"?"active":""} onClick={()=>setFilter("avulso")}>Diaristas</button></nav></header>{rows.length?rows.map(player=>{const name=player.apelido||player.nome,playerHistory=history.filter(row=>row.jogador_id===player.id),stats=[["Peladas",playerHistory.filter(row=>["confirmado","presente","faltou"].includes(row.status)).length],["Presenças",playerHistory.filter(row=>row.status==="presente"||row.comparecimento===true).length],["Faltas",playerHistory.filter(row=>row.status==="faltou").length],["Gols",playerHistory.reduce((total,row)=>total+(row.gols??0),0)],["Assist.",playerHistory.reduce((total,row)=>total+(row.assistencias??0),0)]] as const;return <article key={player.id}><span><b>{name}</b><small>Histórico completo</small></span><div className="player-history" aria-label={`Histórico de ${name}`}>{stats.map(([label,value])=><span key={label}><b>{value}</b><small>{label}</small></span>)}</div><div className="control-badges"><em className={player.ativo?"ok":"off"}>{player.ativo?"Cadastro ativo":"Cadastro suspenso"}</em><em className={player.confirmacao_bloqueada?"off":"ok"}>{player.confirmacao_bloqueada?"Confirmação bloqueada":"Pode confirmar"}</em></div><nav><button className="secondary" onClick={()=>void update(player,{confirmacao_bloqueada:!player.confirmacao_bloqueada},player.confirmacao_bloqueada?"Confirmação liberada.":"Confirmação suspensa.")}>{player.confirmacao_bloqueada?"Liberar confirmação":"Suspender confirmação"}</button><button className={player.ativo?"danger":"secondary"} onClick={()=>void update(player,{ativo:!player.ativo},player.ativo?"Cadastro suspenso.":"Cadastro reativado.")}>{player.ativo?"Suspender cadastro":"Reativar cadastro"}</button><button onClick={()=>void update(player,{tipo:player.tipo==="mensalista"?"avulso":"mensalista"},"Tipo atualizado.")}>Tornar {player.tipo==="mensalista"?"diarista":"mensalista"}</button></nav></article>}):<Empty title="Nenhum jogador neste grupo"/>}<Toast message={toast}/></section>
}
