import { useState } from "react";
import { downloadRecordingFragment, peladaRecordingFragments, peladaRecordingSessions, recordingFragmentUrl, recordingFullUrl, shareRecordingFragment } from "../lib/api";
import type { RecordingFragment, RecordingSession } from "../lib/database.types";
import { useLoad } from "../hooks/useLoad";

type Fragment=RecordingFragment&{session:{device_id:string;started_at:string}};
const label=(item:Fragment)=>`Trecho ${item.sequence_number+1} • ${new Date(item.started_at).toLocaleTimeString("pt-BR",{hour:"2-digit",minute:"2-digit"})}`;
const runUrl=async(setUrl:(url:string)=>void,action:()=>Promise<string>,setNotice:(text:string)=>void)=>{try{setUrl(await action())}catch(error){setNotice(error instanceof Error?error.message:"Não foi possível abrir o vídeo.")}};
export function RecordingGallery({peladaId}:{peladaId:string}){const state=useLoad(async()=>{const[sessions,fragments]=await Promise.all([peladaRecordingSessions(peladaId),peladaRecordingFragments(peladaId)]);return{sessions,fragments}},peladaId),[url,setUrl]=useState(""),[notice,setNotice]=useState("");async function run(action:()=>Promise<void>,message:string){try{await action();setNotice(message)}catch(error){setNotice(error instanceof Error?error.message:"Não foi possível concluir.")}}const data=state.data,{sessions,fragments}=data??{sessions:[] as RecordingSession[],fragments:[] as Fragment[]};if(!state.loading&&!sessions.length&&!fragments.length)return null;return <section className="panel recording-gallery"><p className="eyebrow">VÍDEOS DA PELADA</p><h2>Gravações</h2><small>Vídeo completo e trechos ficam disponíveis para quem participou.</small>{url&&<video className="recording-playback" controls autoPlay playsInline src={url}/>}<div>{sessions.map(item=>{const extension=item.full_mime_type?.includes("mp4")?"mp4":"webm";return <article key={item.id}><span><b>Vídeo completo</b><small>{new Date(item.started_at).toLocaleString("pt-BR")} • {item.full_byte_size?`${(item.full_byte_size/1024/1024).toFixed(1)} MB`:"processando"}</small></span><nav><button className="mini secondary" onClick={()=>void runUrl(setUrl,()=>recordingFullUrl(item.id),setNotice)}>ASSISTIR</button><button className="mini secondary" onClick={()=>void run(()=>recordingFullUrl(item.id,600,`video-completo.${extension}`).then(url=>{const link=document.createElement("a");link.href=url;link.click()}),"Download iniciado.")}>BAIXAR</button></nav></article>})}{fragments.map(item=><article key={item.id}><span><b>{label(item)}</b><small>Câmera {item.session.device_id.slice(-6)} • {(item.byte_size/1024/1024).toFixed(1)} MB</small></span><nav><button className="mini secondary" onClick={()=>void runUrl(setUrl,()=>recordingFragmentUrl(item.storage_path),setNotice)}>ASSISTIR</button><button className="mini secondary" onClick={()=>void run(()=>downloadRecordingFragment(item.storage_path,`${label(item)}.${item.mime_type.includes("mp4")?"mp4":"webm"}`),"Download iniciado.")}>BAIXAR</button><button className="mini" onClick={()=>void run(()=>shareRecordingFragment(item.storage_path,label(item)),"Link pronto para compartilhar.")}>COMPARTILHAR</button></nav></article>)}</div>{state.error&&<small>{state.error}</small>}{notice&&<small className="recording-gallery-notice">{notice}</small>}</section>}
