import { createClient } from "jsr:@supabase/supabase-js@2";

const cors={"Access-Control-Allow-Origin":"*","Access-Control-Allow-Headers":"authorization,apikey,content-type","Access-Control-Allow-Methods":"POST,OPTIONS"},encoder=new TextEncoder();
const json=(body:unknown,status=200)=>new Response(JSON.stringify(body),{status,headers:{...cors,"Content-Type":"application/json"}});
const encode=(value:string)=>encodeURIComponent(value).replace(/[!'()*]/g,char=>`%${char.charCodeAt(0).toString(16).toUpperCase()}`);
const hex=(value:ArrayBuffer)=>Array.from(new Uint8Array(value)).map(byte=>byte.toString(16).padStart(2,"0")).join("");
const hash=async(value:ArrayBuffer|string)=>hex(await crypto.subtle.digest("SHA-256",typeof value==="string"?encoder.encode(value):value));
const hmac=async(key:ArrayBuffer|string,data:string)=>crypto.subtle.sign("HMAC",await crypto.subtle.importKey("raw",typeof key==="string"?encoder.encode(key):key,{name:"HMAC",hash:"SHA-256"},false,["sign"]),encoder.encode(data));

Deno.serve(async req=>{if(req.method==="OPTIONS")return new Response("ok",{headers:cors});try{const url=Deno.env.get("SUPABASE_URL")!,anon=Deno.env.get("SUPABASE_ANON_KEY")!,service=Deno.env.get("SUPABASE_SERVICE_ROLE_KEY")!,caller=createClient(url,anon,{global:{headers:{Authorization:req.headers.get("Authorization")??""}}}),admin=createClient(url,service),{data:{user}}=await caller.auth.getUser();if(!user)throw new Error("Não autenticado");const body=await req.json().catch(()=>({})),action=body.action??"copy";
  if(action==="url")return json({url:await fragmentUrl(admin,user.id,String(body.path??""),Number(body.expires??600),typeof body.download_name==="string"?body.download_name:undefined)});
  if(action==="full_url")return json({url:await fullUrl(admin,user.id,String(body.session_id??""),Number(body.expires??600),typeof body.download_name==="string"?body.download_name:undefined)});
  if(action==="cut_url")return json({url:await cutUrl(admin,user.id,String(body.cut_id??""),Number(body.expires??600),typeof body.download_name==="string"?body.download_name:undefined)});
  const{data:profile,error:profileError}=await admin.from("profiles").select("role").eq("id",user.id).single();if(profileError||profile?.role!=="superadmin")throw new Error("Acesso negado");
  if(action==="copy_full")return json(await copyFull(admin,user.id,String(body.session_id??"")));
  if(action==="copy_cut")return json(await copyCut(admin,user.id,String(body.cut_id??"")));
  return json(await copyFragments(admin,user.id,typeof body.session_id==="string"?body.session_id:null,typeof body.fragment_id==="string"?body.fragment_id:null));
}catch(error){const message=error instanceof Error?error.message:"Falha ao enviar a gravação";console.error(message);return json({error:message},500)}});

async function copyFragments(admin:ReturnType<typeof createClient>,userId:string,sessionId:string|null,fragmentId:string|null){if(!sessionId&&!fragmentId)throw new Error("Informe a gravação");let query=admin.from("recording_fragments").select("id,storage_path,mime_type,r2_key,sequence_number,session:recording_sessions!inner(id,admin_id,pelada_id)");query=fragmentId?query.eq("id",fragmentId):query.eq("session_id",sessionId!);const{data,error}=await query;if(error)throw error;let uploaded=0;for(const item of data??[]){const fragment=item as unknown as {id:string;storage_path:string;mime_type:string;r2_key:string|null;sequence_number:number;session:{id:string;admin_id:string;pelada_id:string}};if(fragment.session.admin_id!==userId)throw new Error("Acesso negado");if(fragment.r2_key)continue;const{data:file,error:fileError}=await admin.storage.from("pelada-gravacoes").download(fragment.storage_path);if(fileError)throw fileError;const match=await runningMatch(admin,fragment.session.pelada_id),number=match?.sequence_number??0,extension=fragment.mime_type.includes("mp4")?"mp4":"webm",key=`pelada_${fragment.session.pelada_id}/partida_${String(number).padStart(2,"0")}/trechos/partida_${String(number).padStart(2,"0")}_trecho_${String(fragment.sequence_number+1).padStart(3,"0")}.${extension}`;await putR2(key,file,fragment.mime_type);const{error:updateError}=await admin.from("recording_fragments").update({r2_key:key,r2_uploaded_at:new Date().toISOString(),r2_error:null}).eq("id",fragment.id);if(updateError)throw updateError;await admin.storage.from("pelada-gravacoes").remove([fragment.storage_path]);uploaded++}if(sessionId)await admin.from("recording_sessions").update({upload_status:"UPLOADED"}).eq("id",sessionId);return{configured:true,uploaded}}
async function copyFull(admin:ReturnType<typeof createClient>,userId:string,sessionId:string){if(!sessionId)throw new Error("Informe a gravação");const{data,error}=await admin.from("recording_sessions").select("id,admin_id,pelada_id,full_storage_path,full_mime_type,full_r2_key").eq("id",sessionId).single();if(error||!data)throw new Error("Gravação não encontrada");const session=data as {id:string;admin_id:string;pelada_id:string;full_storage_path:string|null;full_mime_type:string|null;full_r2_key:string|null};if(session.admin_id!==userId)throw new Error("Acesso negado");if(session.full_r2_key)return{configured:true,uploaded:0};if(!session.full_storage_path)throw new Error("Vídeo completo não encontrado");const{data:file,error:fileError}=await admin.storage.from("pelada-gravacoes").download(session.full_storage_path);if(fileError)throw fileError;const extension=session.full_mime_type?.includes("mp4")?"mp4":"webm",key=`pelada_${session.pelada_id}/video_completo_${session.id}.${extension}`;await putR2(key,file,session.full_mime_type??(file.type||"video/webm"));const{error:updateError}=await admin.from("recording_sessions").update({full_r2_key:key,upload_status:"UPLOADED"}).eq("id",session.id);if(updateError)throw updateError;await admin.storage.from("pelada-gravacoes").remove([session.full_storage_path]);return{configured:true,uploaded:1}}
async function copyCut(admin:ReturnType<typeof createClient>,userId:string,cutId:string){if(!cutId)throw new Error("Informe o corte");const{data,error}=await admin.from("recording_cuts").select("id,session_id,event_id,clip_start_ms,clip_end_ms,status,r2_key,session:recording_sessions!inner(admin_id,pelada_id,started_at,status)").eq("id",cutId).single();if(error||!data)throw new Error("Corte não encontrado");const cut=data as unknown as {id:string;session_id:string;event_id:string;clip_start_ms:number;clip_end_ms:number;status:string;r2_key:string|null;session:{admin_id:string;pelada_id:string;started_at:string;status:string}};if(cut.session.admin_id!==userId)throw new Error("Acesso negado");if(cut.r2_key)return{configured:true,uploaded:0};const{data:event,error:eventError}=await admin.from("pelada_eventos_partida").select("id,type,status,match_id,team_id,corrected_created_at").eq("id",cut.event_id).single();if(eventError||!event)throw new Error("Evento não encontrado");if(event.status!=="ACTIVE"){await admin.from("recording_cuts").update({status:"CANCELLED"}).eq("id",cut.id);return{configured:true,uploaded:0}}const{data:match,error:matchError}=await admin.from("pelada_partidas").select("sequence_number,team_home,team_away").eq("id",event.match_id).single();if(matchError||!match)throw new Error("Partida não encontrada");const{data:fragments,error:fragmentError}=await admin.from("recording_fragments").select("r2_key,mime_type,started_at,duration_ms,sequence_number").eq("session_id",cut.session_id).not("r2_key","is",null).order("sequence_number");if(fragmentError)throw fragmentError;const selected=(fragments??[]).filter(item=>{const start=new Date(item.started_at).getTime()-new Date(cut.session.started_at).getTime(),end=start+item.duration_ms;return start<cut.clip_end_ms&&end>cut.clip_start_ms});if(!selected.length||(cut.session.status==="RECORDING"&&Math.max(...selected.map(item=>new Date(item.started_at).getTime()-new Date(cut.session.started_at).getTime()+item.duration_ms))<cut.clip_end_ms))return{configured:true,uploaded:0,pending:true};
  // ponytail: chunk-aligned clips; add transcoding only if frame-exact edits are required.
  const buffers=await Promise.all(selected.map(async item=>{const response=await fetch(await signGet(item.r2_key!,600));if(!response.ok)throw new Error("Não foi possível ler um trecho");return response.arrayBuffer()})),mimeType=selected[0].mime_type,extension=mimeType.includes("mp4")?"mp4":"webm",name=await cutName(admin,event as {type:string;match_id:string;team_id:number|null;corrected_created_at:string},match as {sequence_number:number;team_home:number;team_away:number}),key=`pelada_${cut.session.pelada_id}/partida_${String(match.sequence_number).padStart(2,"0")}/clipes/${name}.${extension}`,file=new Blob(buffers,{type:mimeType});await putR2(key,file,mimeType);const{error:updateError}=await admin.from("recording_cuts").update({status:"COMPLETED",output_path:key,r2_key:key,mime_type:mimeType,byte_size:file.size,error_message:null}).eq("id",cut.id);if(updateError)throw updateError;return{configured:true,uploaded:1}}
async function cutName(admin:ReturnType<typeof createClient>,event:{type:string;match_id:string;team_id:number|null;corrected_created_at:string},match:{sequence_number:number;team_home:number;team_away:number}){const prefix=`partida_${String(match.sequence_number).padStart(2,"0")}`;if(event.type!=="GOAL"){const{count}=await admin.from("pelada_eventos_partida").select("id",{count:"exact",head:true}).eq("match_id",event.match_id).eq("type","HIGHLIGHT").eq("status","ACTIVE").lte("corrected_created_at",event.corrected_created_at);return `${prefix}_lance_${String(count??1).padStart(2,"0")}`}const[{count:home},{count:away}]=await Promise.all([admin.from("pelada_eventos_partida").select("id",{count:"exact",head:true}).eq("match_id",event.match_id).eq("type","GOAL").eq("status","ACTIVE").eq("team_id",match.team_home).lte("corrected_created_at",event.corrected_created_at),admin.from("pelada_eventos_partida").select("id",{count:"exact",head:true}).eq("match_id",event.match_id).eq("type","GOAL").eq("status","ACTIVE").eq("team_id",match.team_away).lte("corrected_created_at",event.corrected_created_at)]);return `${prefix}_${home??0}x${away??0}`}
async function runningMatch(admin:ReturnType<typeof createClient>,peladaId:string){const{data}=await admin.from("pelada_partidas").select("sequence_number").eq("pelada_id",peladaId).eq("status","RUNNING").maybeSingle();return data as {sequence_number:number}|null}
function config(){const endpoint=Deno.env.get("R2_ENDPOINT")?.replace(/\/$/,""),bucket=Deno.env.get("R2_BUCKET"),access=Deno.env.get("R2_ACCESS_KEY_ID"),secret=Deno.env.get("R2_SECRET_ACCESS_KEY");if(!endpoint||!bucket||!access||!secret)throw new Error("Configure os secrets do Cloudflare R2 no Supabase");return{endpoint,bucket,access,secret}}
function stamp(){const now=new Date(),iso=now.toISOString().replace(/[:-]|\.\d{3}/g,""),date=iso.slice(0,8);return{iso,date}}
function resource(endpoint:string,bucket:string,path:string){const base=new URL(endpoint),key=path.split("/").map(encode).join("/");return{url:`${base.origin}/${encode(bucket)}/${key}`,host:base.host,uri:`/${encode(bucket)}/${key}`}}
async function putR2(path:string,file:Blob,mimeType:string){const{endpoint,bucket,access,secret}=config(),{iso,date}=stamp(),target=resource(endpoint,bucket,path),payload=await file.arrayBuffer(),payloadHash=await hash(payload),headers=`content-type:${mimeType}\nhost:${target.host}\nx-amz-content-sha256:${payloadHash}\nx-amz-date:${iso}\n`,signed="content-type;host;x-amz-content-sha256;x-amz-date",canonical=`PUT\n${target.uri}\n\n${headers}\n${signed}\n${payloadHash}`,scope=`${date}/auto/s3/aws4_request`,toSign=`AWS4-HMAC-SHA256\n${iso}\n${scope}\n${await hash(canonical)}`,key=await signingKey(secret,date),signature=hex(await hmac(key,toSign)),authorization=`AWS4-HMAC-SHA256 Credential=${access}/${scope}, SignedHeaders=${signed}, Signature=${signature}`,response=await fetch(target.url,{method:"PUT",headers:{"Content-Type":mimeType,Host:target.host,"x-amz-content-sha256":payloadHash,"x-amz-date":iso,Authorization:authorization},body:payload});if(!response.ok)throw new Error(`R2 recusou o envio: ${await response.text()}`)}
async function signingKey(secret:string,date:string){const dateKey=await hmac(`AWS4${secret}`,date),region=await hmac(dateKey,"auto"),service=await hmac(region,"s3");return hmac(service,"aws4_request")}
async function fragmentUrl(admin:ReturnType<typeof createClient>,userId:string,path:string,expires:number,downloadName?:string){if(!path)throw new Error("Vídeo não informado");const{data,error}=await admin.from("recording_fragments").select("storage_path,r2_key,session:recording_sessions!inner(pelada_id)").eq("storage_path",path).maybeSingle();if(error||!data)throw new Error("Vídeo não encontrado");const item=data as unknown as {storage_path:string;r2_key:string|null;session:{pelada_id:string}};if(!await canRead(admin,userId,item.session.pelada_id))throw new Error("Acesso negado");return item.r2_key?signGet(item.r2_key,expires,downloadName):storageUrl(admin,item.storage_path,expires,downloadName)}
async function fullUrl(admin:ReturnType<typeof createClient>,userId:string,sessionId:string,expires:number,downloadName?:string){const{data,error}=await admin.from("recording_sessions").select("pelada_id,full_storage_path,full_r2_key").eq("id",sessionId).maybeSingle();if(error||!data)throw new Error("Vídeo não encontrado");const item=data as {pelada_id:string;full_storage_path:string|null;full_r2_key:string|null};if(!await canRead(admin,userId,item.pelada_id))throw new Error("Acesso negado");if(item.full_r2_key)return signGet(item.full_r2_key,expires,downloadName);if(!item.full_storage_path)throw new Error("Vídeo completo ainda não foi enviado");return storageUrl(admin,item.full_storage_path,expires,downloadName)}
async function cutUrl(admin:ReturnType<typeof createClient>,userId:string,cutId:string,expires:number,downloadName?:string){const{data,error}=await admin.from("recording_cuts").select("r2_key,output_path,session:recording_sessions!inner(pelada_id)").eq("id",cutId).maybeSingle();if(error||!data)throw new Error("Clipe não encontrado");const item=data as unknown as {r2_key:string|null;output_path:string|null;session:{pelada_id:string}};if(!await canRead(admin,userId,item.session.pelada_id))throw new Error("Acesso negado");const key=item.r2_key??item.output_path;if(!key)throw new Error("Clipe ainda está sendo preparado");return signGet(key,expires,downloadName)}
async function storageUrl(admin:ReturnType<typeof createClient>,path:string,expires:number,downloadName?:string){const{data,error}=await admin.storage.from("pelada-gravacoes").createSignedUrl(path,Math.min(Math.max(expires,60),604800),downloadName?{download:downloadName}:undefined);if(error)throw error;return data.signedUrl}
async function canRead(admin:ReturnType<typeof createClient>,userId:string,peladaId:string){const{data:profile}=await admin.from("profiles").select("role").eq("id",userId).single();if(profile?.role==="admin"||profile?.role==="superadmin")return true;const{data:operator}=await admin.from("pelada_operadores").select("user_id").eq("pelada_id",peladaId).eq("user_id",userId).maybeSingle();if(operator)return true;const{data:direct}=await admin.from("pelada_participantes").select("id").eq("pelada_id",peladaId).eq("user_id",userId).or("status.in.(confirmado,presente),comparecimento.eq.true").limit(1).maybeSingle();if(direct)return true;const{data:players}=await admin.from("jogadores").select("id").eq("user_id",userId);if(!players?.length)return false;const{data:linked}=await admin.from("pelada_participantes").select("id").eq("pelada_id",peladaId).in("jogador_id",players.map(player=>player.id)).or("status.in.(confirmado,presente),comparecimento.eq.true").limit(1).maybeSingle();return Boolean(linked)}
async function signGet(path:string,expires:number,downloadName?:string){const{endpoint,bucket,access,secret}=config(),{iso,date}=stamp(),target=resource(endpoint,bucket,path),scope=`${date}/auto/s3/aws4_request`,params:[string,string][]=[["X-Amz-Algorithm","AWS4-HMAC-SHA256"],["X-Amz-Credential",`${access}/${scope}`],["X-Amz-Date",iso],["X-Amz-Expires",String(Math.min(Math.max(expires,60),604800))],["X-Amz-SignedHeaders","host"]];if(downloadName)params.push(["response-content-disposition",`attachment; filename="${downloadName.replace(/["\\]/g,"_")}"`]);const query=params.sort(([a],[b])=>a.localeCompare(b)).map(([key,value])=>`${encode(key)}=${encode(value)}`).join("&"),canonical=`GET\n${target.uri}\n${query}\nhost:${target.host}\n\nhost\nUNSIGNED-PAYLOAD`,toSign=`AWS4-HMAC-SHA256\n${iso}\n${scope}\n${await hash(canonical)}`,signature=hex(await hmac(await signingKey(secret,date),toSign));return `${target.url}?${query}&X-Amz-Signature=${signature}`}
